apiVersion: v1
kind: ConfigMap
metadata:
  name: springapp-config
  namespace: app-namespace
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://postgre-service:1234/Kube
    spring.datasource.username=postgres
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
---
apiVersion: v1
kind: Secret
metadata:
  name: springapp-secret
  namespace: app-namespace
type: Opaque
data:
  spring.datasource.password: Ym9yaXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-pod
  template:
    metadata:
      labels:
        app: spring-pod
    spec:
      containers:
        - name: spring
          image: saranikolova54932/spring-boot-app
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /etc/config/
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springapp-secret
                  key: spring.datasource.password
          volumeMounts:
            - name: springapp-config-volume
              mountPath: /etc/config
              readOnly: true
            - name: springapp-secret-volume
              mountPath: /etc/secret
              readOnly: true
      volumes:
        - name: springapp-config-volume
          configMap:
            name: springapp-config
        - name: springapp-secret-volume
          secret:
            secretName: springapp-secret
