apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: app-namespace
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: boris
  POSTGRES_DB: Kube

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: app-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: app-namespace
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: app-namespace
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: saranikolova54932/data-base
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc