apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: app-namespace
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://db:5432/Kube
    spring.datasource.username=postgres
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

---

apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: app-namespace
type: Opaque
data:
  spring.datasource.password: Ym9yaXM=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-pod
  template:
    metadata:
      labels:
        app: spring-pod
    spec:
      containers:
        - name: spring-container
          image: saranikolova54932/spring-boot-app
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /etc/config/
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: spring.datasource.password
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
            - name: secret-volume
              mountPath: /etc/secret
              readOnly: true

      volumes:
        - name: config-volume
          configMap:
            name: spring-config
        - name: secret-volume
          secret:
            secretName: spring-secret